---
- hosts: servers
  tasks:
  - name: OS:"{{ ansible_distribution }}" Version:"{{ansible_distribution_major_version}}" 
    ping:
- hosts: centos6
  tasks:
    # task 1
    - name: test connection
      ping:
      register: message

    # task 2
    - name: print debug message
      debug:
        msg: "{{ message }}"