---
- name: restart sshd 7
  ansible.builtin.systemd:
    state: restarted
    name: sshd
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: restart sshd 6
  ansible.builtin.service:
    state: restarted
    name: sshd
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"