# ▪  這項原則設定決定是否設定SSH主機公鑰檔案權限
# ▪  SSH主機公鑰是SSH協定中驗證主機所使用的加密金鑰，搭配公鑰與私鑰可驗證使用者身分
# ▪  設定SSH主機公鑰檔案權限，避免遭未經授權的使用者修改檔案，導致主機SSH服務無法正常運作
---
- name: TWGCB-01-008-0270
  become: yes
  command: find /etc/ssh -xdev -type f -name 'ssh_host_*_key.pub' -exec chmod 644 {} \;