---
- name: push /etc/ssh/sshd_config
  become: yes
  copy:
    src: files/{{ansible_distribution}}{{ansible_distribution_major_version}}/etc/ssh/sshd_config
    dest: /etc/ssh
    owner: root
    group: root
    mode: 0600

- include_tasks: ./tasks/restartSshd.yml