---
# - include_tasks: TWGCB-01-008-0001.yml
# - include_tasks: TWGCB-01-008-0002.yml
# - include_tasks: TWGCB-01-008-0003.yml

- name: TWGCB-01-008-CentOS7
  include_tasks: TWGCB-01-008-tmp-CentOS7.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: TWGCB-01-008-CentOS6
  include_tasks: TWGCB-01-008-tmp-CentOS6.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"