---
# - include_tasks: TWGCB-01-008-0001.yml
# - include_tasks: TWGCB-01-008-0002.yml
# - include_tasks: TWGCB-01-008-0003.yml

# - name: TWGCB-01-008 copy fstab
#   become: yes
#   copy:
#     src: files/servers/{{server_name}}/etc/fstab
#     dest: /etc
#     owner: root
#     group: root
#     mode: 0644

# - name: TWGCB-01-008-tmp-CentOS7
#   include_tasks: TWGCB-01-008-tmp-CentOS7.yml
#   when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

# - name: TWGCB-01-008-tmp-CentOS6
#   include_tasks: TWGCB-01-008-tmp-CentOS6.yml
#   when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"

# - include_tasks: TWGCB-01-008-dev-shm.yml
# - include_tasks: TWGCB-01-008-home.yml

# - include_tasks: TWGCB-01-008-0029.yml Ansible 會出錯暫時手動處理

# - include_tasks: TWGCB-01-008-0031.yml
# - include_tasks: TWGCB-01-008-0032.yml

# - name: TWGCB-01-008-0033 install sudo
#   become: yes
#   yum:
#     name: sudo
#     state: latest
#   when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

# - name: TWGCB-01-008-0037  
#   include_tasks: TWGCB-01-008-0037.yml
#   when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

# - include_tasks: TWGCB-01-008-0047.yml
# - include_tasks: TWGCB-01-008-0055.yml
# - include_tasks: TWGCB-01-008-0057.yml
# - include_tasks: TWGCB-01-008-0059.yml
# - include_tasks: TWGCB-01-008-0073.yml
# - include_tasks: TWGCB-01-008-0092.yml

# - name: TWGCB-01-008-tmp-CentOS6
#   include_tasks: TWGCB-01-008-0093.yml
#   when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

# - include_tasks: TWGCB-01-008-0098.yml
# - include_tasks: TWGCB-01-008-0101.yml
# - include_tasks: TWGCB-01-008-0102.yml
# - include_tasks: TWGCB-01-008-0126.yml
# - include_tasks: TWGCB-01-008-0127.yml
# - include_tasks: TWGCB-01-008-0128.yml
# - include_tasks: TWGCB-01-008-0129.yml
# - include_tasks: TWGCB-01-008-0136.yml
# - include_tasks: TWGCB-01-008-0177.yml

# - include_tasks: TWGCB-01-008-rules.yml
# - include_tasks: TWGCB-01-008-service-disable.yml
# - include_tasks: TWGCB-01-008-service-enable.yml
# - include_tasks: TWGCB-01-008-service-restart.yml
- include_tasks: TWGCB-01-008-chmod-file-0600.yml
# - include_tasks: TWGCB-01-008-chmod-file-0640.yml
# - include_tasks: TWGCB-01-008-chmod-file-0700.yml
- include_tasks: TWGCB-01-008-chmod-file-0740.yml
# - include_tasks: TWGCB-01-008-remove-package.yml
# - include_tasks: TWGCB-01-008-logs.yml
# - include_tasks: TWGCB-01-008-auditd.yml
# - include_tasks: TWGCB-01-008-etc-passwd.yml
# - include_tasks: TWGCB-01-008-etc-gshadow.yml
# - include_tasks: TWGCB-01-008-etc-group.yml
- include_tasks: TWGCB-01-008-etc-selinux.yml
# - include_tasks: TWGCB-01-008-sysctl.yml
# - include_tasks: TWGCB-01-008-sudo.yml

