# TWGCB-01-008-0097
# ▪  這項原則設定決定是否啟用squid服務，以運行代理伺服器功能
# ▪  攻擊者透過代理伺服器攻擊其他伺服器時，可以藉此隱匿身分，甚至進而進入到其他受保護的網段中
# ▪  停用Squid服務可降低系統被攻擊面
---
- name: TWGCB-01-008-0097 in CentOS 8
  become: yes 
  ansible.builtin.systemd:
    name: squid
    enabled: no
    state: stopped
  ignore_errors: yes
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "8"
  
- name: TWGCB-01-008-0097 in CentOS 7
  become: yes 
  ansible.builtin.systemd:
    name: squid
    enabled: no
    state: stopped
  ignore_errors: yes
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: TWGCB-01-008-0097 in CentOS 6
  become: yes 
  ansible.builtin.service:
    name: squid
    enabled: no
    state: stopped
  ignore_errors: yes
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"


