# ▪  這項原則設定決定是否支援squashfs檔案系統
# ▪  squashfs是一個即時解壓縮之檔案系統，專門為唯讀壓縮檔案系統之使用而設計，常見於各Linux發行版之LiveCD
# ▪  停止支援squashfs檔案系統，以降低系統被攻擊面
---

- name: TWGCB-01-008-0002 Check that the squashfs.conf exists
  stat:
    path: /etc/modprobe.d/squashfs.conf
  register: file_status

- name: TWGCB-01-008-0002 creat squashfs.conf
  become: yes
  copy:
    src: files/{{ansible_distribution}}{{ansible_distribution_major_version}}/etc/modprobe.d/squashfs.conf
    dest: /etc/modprobe.d
    owner: root
    group: root
    mode: 0644
  when: file_status.stat.exists == False
  
- name: TWGCB-01-008-0002 Check that if the file squashfs.conf exists
  debug:
    msg: "File exists. Need people check TWGCB-01-008-0002"
  when: file_status.stat.exists == True

- name: TWGCB-01-008-0002 remove squashfs
  become: yes
  command: rmmod squashfs
  ignore_errors: yes

