# TWGCB-01-008-0051
# ▪  這項原則設定決定/etc/gshadow檔案擁有者與群組
# ▪  /etc/gshadow記錄每個群組加密過後的密碼，以及使用者與管理者資訊，攻擊者讀取/etc/gshadow檔案後，可嘗試透過密碼破解程式取得密碼後進行攻擊
# ▪  設定/etc/gshadow檔案擁有者與群組，以保護群組帳號密碼資訊，降低檔案被竄改後進一步利用於其他惡意攻擊之風險
# TWGCB-01-008-0052
# ▪  這項原則設定決定/etc/gshadow檔案權限
# ▪  /etc/gshadow記錄每個群組加密過後的密碼，以及使用者與管理者資訊，攻擊者讀取/etc/gshadow檔案後，可嘗試透過密碼破解程式取得密碼後進行攻擊
# ▪  設定/etc/gshadow檔案權限為000(所有使用者不具有讀取、寫入及執行權限)，以保護群組帳號密碼資訊，降低檔案被竄改後進一步利用於其他惡意攻擊之風險
---

- name: TWGCB-01-008-0051:TWGCB-01-008-0052 /etc/gshadow
  become: yes
  ansible.builtin.file:
    path: /etc/gshadow
    owner: root
    group: root
    mode: '0000'
