# ▪  這項原則設定決定是否使用AIDE工具定期檢查檔案系統完整性
# ▪  AIDE截取檔案系統狀態的快照，包括修改時間、權限及檔案雜湊，藉由將快照與檔案系統的當前狀態進行比較，以檢測系統變更情況，找出被修改或損毀的檔案
# ▪  定期檢查檔案系統完整性，可協助系統管理者定期確認是否有重要檔案在未經授權的情況下被修改

---

- name: TWGCB-01-008-0037 install aide
  yum:
    name: aide
    state: latest

- name: TWGCB-01-008-0037
  become: yes
  ansible.builtin.cron:
    name: "TWGCB-01-008-0037"
    minute: "0"
    hour: "5"
    job: "/usr/sbin/aide --check"
