# ▪  這項原則設定決定是否啟用RDS協定
# ▪  RDS(Reliable Datagram Sockets)協定是由甲骨文(Oracle)發展的協定，提供節點與叢集間可靠的高效能與低延遲通訊，應用在VoIP網路電話
# ▪  停用此協定可降低系統被攻擊面

---

- name: TWGCB-01-008-0128 Check that the rds.conf exists
  stat:
    path: /etc/modprobe.d/rds.conf
  register: file_status

- name: TWGCB-01-008-0128 creat rds.conf
  become: yes
  copy:
    src: files/{{ansible_distribution}}{{ansible_distribution_major_version}}/etc/modprobe.d/rds.conf
    dest: /etc/modprobe.d
    owner: root
    group: root
    mode: 0644
  when: file_status.stat.exists == False
  
- name: TWGCB-01-008-0128 Check that if the file rds.conf exists
  debug:
    msg: "File exists. Need people check TWGCB-01-008-0128"
  when: file_status.stat.exists == True


