---

- name: TWGCB-01-008-etc-selinux selinux/config
  become: yes
  copy:
    src: files/{{ansible_distribution}}{{ansible_distribution_major_version}}/etc/selinux/config
    dest: /etc/selinux
    owner: root
    group: root
    mode: 0644