---

- name: TWGCB-01-008-rules
  become: yes
  copy:
    src: files/{{ansible_distribution}}{{ansible_distribution_major_version}}/etc/audit/rules.d/gcb.rules
    dest: /etc/audit/rules.d
    owner: root
    group: root
    mode: 0640

