# TWGCB-01-008-0073
# ▪  這項原則設定決定是否允許root帳號的路徑(PATH)變數存在相對路徑或空目錄(例如：「.」、「..」、路徑開頭不是「/」及空元素)
# ▪  root帳號可以執行系統上所有指令，若PATH設定錯誤，root將可能執行到偽裝的程式檔案，危害系統安全
# .：目前目錄
# ..：上一層目錄
---
- name: TWGCB-01-008-0073 copy tmp.mount
  become: yes
  copy:
    src: files/servers/{{server_name}}/etc/profile
    dest: /etc
    owner: root
    group: root
    mode: 0644
