# TWGCB-01-008-0055
# `▪  這項原則設定決定/etc/shadow-檔案擁有者與群組
# `▪  /etc/shadow-備份每個使用者帳號加密過後的密碼、最後變更密碼的日期及下次可變更密碼前的經過天數等資訊
# `▪  若攻擊者取得/etc/shadow-檔案，可嘗試透過密碼破解程式取得密碼後進行攻擊
# `▪  設定/etc/shadow-檔案所有權，以保護帳號密碼資訊，降低檔案被竄改後進一步利用於其他惡意攻擊之風險
# `TWGCB-01-008-0056
# `▪  這項原則設定決定/etc/shadow-檔案權限
# `▪  /etc/shadow-備份每個使用者帳號加密過後的密碼、最後變更密碼的日期及下次可變更密碼前的經過天數等資訊
# `▪  若攻擊者取得/etc/shadow-檔案，可嘗試透過密碼破解程式取得密碼後進行攻擊
# `▪  設定/etc/shadow-檔案權限為000(所有使用者不具有讀取、寫入及執行權限)，以保護帳號密碼資訊，降低檔案被竄改後進一步利用於其他惡意攻擊之風險
---
- name: TWGCB-01-008-0055:TWGCB-01-008-0056 /etc/shadow-
  become: yes
  ansible.builtin.file:
    path: /etc/shadow-
    owner: root
    group: root
    mode: '0000'
