# TWGCB-01-008-0057
# ▪  這項原則設定決定/etc/group-檔案擁有者與群組
# ▪  /etc/group-備份每個群組的名稱、密碼、ID及屬於該群組的使用者清單
# ▪  設定/etc/group-檔案擁有者與群組為root，避免/etc/group-檔案遭未授權使用者修改
# TWGCB-01-008-0058
# ▪  這項原則設定決定/etc/group-檔案權限
# ▪  /etc/group-備份每個群組的名稱、密碼、ID及屬於該群組的使用者清單
# ▪  設定/etc/group-檔案權限，僅root擁有讀取與寫入權限，其餘所有使用者僅可讀取，避免/etc/group-檔案遭未授權使用者修改
---

- name: TWGCB-01-008-0057:TWGCB-01-008-0058 /etc/group-
  become: yes
  ansible.builtin.file:
    path: /etc/group-
    owner: root
    group: root
    mode: '0644'
