# ▪  這項原則設定決定是否啟用SCTP協定
# ▪  SCTP協定(Stream Control Transmission Protocol，資料流控制傳輸協定)屬於傳輸層通訊協定，支援訊息導向通訊，並結合了TCP與UDP的特點，提高資料傳輸可靠性與效率
# ▪  停用此協定可降低系統被攻擊面

---

- name: TWGCB-01-008-0127 Check that the sctp.conf exists
  stat:
    path: /etc/modprobe.d/sctp.conf
  register: file_status

- name: TWGCB-01-008-0127 creat sctp.conf
  become: yes
  copy:
    src: files/{{ansible_distribution}}{{ansible_distribution_major_version}}/etc/modprobe.d/sctp.conf
    dest: /etc/modprobe.d
    owner: root
    group: root
    mode: 0644
  when: file_status.stat.exists == False
  
- name: TWGCB-01-008-0127 Check that if the file sctp.conf exists
  debug:
    msg: "File exists. Need people check TWGCB-01-008-0127"
  when: file_status.stat.exists == True

