# ▪  這項原則設定決定是否啟用TIPC協定
# ▪  TIPC(Transparent Inter-Process Communication，透通處理程序間通訊)協定提供一個有效率的叢集式通訊協定，提高系統效能、可用性及擴展性
# ▪  停用此協定可降低系統被攻擊面
---

- name: TWGCB-01-008-0129 Check that the tipc.conf exists
  stat:
    path: /etc/modprobe.d/tipc.conf
  register: file_status

- name: TWGCB-01-008-0129 creat tipc.conf
  become: yes
  copy:
    src: files/{{ansible_distribution}}{{ansible_distribution_major_version}}/etc/modprobe.d/tipc.conf
    dest: /etc/modprobe.d
    owner: root
    group: root
    mode: 0644
  when: file_status.stat.exists == False
  
- name: TWGCB-01-008-0129 Check that if the file tipc.conf exists
  debug:
    msg: "File exists. Need people check TWGCB-01-008-0129"
  when: file_status.stat.exists == True
