---

- name: TWGCB-01-008-sudo Check that the gcb exists
  become: yes
  stat:
    path: /etc/sudoers.d/gcb
  register: file_status

- name: TWGCB-01-008-sudo creat sudo
  become: yes
  copy:
    src: files/{{ansible_distribution}}{{ansible_distribution_major_version}}/etc/sudoers.d/gcb
    dest: /etc/sudoers.d
    owner: root
    group: root
    mode: 0440
  when: file_status.stat.exists == False
  
- name: TWGCB-01-008-sduo Check that if the file sudo exists
  debug:
    msg: "File exists. Need people check TWGCB-01-008-sudo"
  when: file_status.stat.exists == True
