# 停用服務列表

- name: service-disable in CentOS 8
  become: yes 
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: no
    state: stopped
  ignore_errors: yes
  loop: "{{ service_disable }}"
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "8"

- name: service-disable in CentOS 7
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  ignore_errors: yes
  loop: "{{ service_disable }}"
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: service-disable in CentOS 6
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  ignore_errors: yes
  loop: "{{ service_disable }}"
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"