# ▪  這項原則設定決定是否支援udf檔案系統
# ▪  udf(Universal disk format，通用磁碟格式)是根據ISO/IEC 13346與ECMA-167標準所實做之檔案系統，由光學儲存技術協會(OSTA)開發與維護，廣泛應用在如CD-R/RW與DVD-R/RW等可寫光學儲存媒體
# ▪  停止支援udf檔案系統，以降低系統被攻擊面
---

- name: TWGCB-01-008-0003 Check that the udf.conf exists
  stat:
    path: /etc/modprobe.d/udf.conf
  register: file_status

- name: TWGCB-01-008-0003 creat udf.conf
  become: yes
  copy:
    src: files/{{ansible_distribution}}{{ansible_distribution_major_version}}/etc/modprobe.d/udf.conf
    dest: /etc/modprobe.d
    owner: root
    group: root
    mode: 0644
  when: file_status.stat.exists == False
  
- name: TWGCB-01-008-0003 Check that if the file udf.conf exists
  debug:
    msg: "File exists. Need people check TWGCB-01-008-0003"
  when: file_status.stat.exists == True

- name: TWGCB-01-008-0003 remove udf
  become: yes
  command: rmmod udf
  ignore_errors: yes

